on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Testing GitHub action"
        run: pwd
      - name: "Testing Printing"
        run: echo Rana
      - name: "Printing folder contents"
        run: ls
      - uses: actions/checkout@v3
      - name: "Printing folder contents after uses"
        run: ls
      - name: " login to docker"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOKEN}}
